---
- hosts: all
  become: yes
  become_user: root

  tasks:
  - name: Install libselinux-python, and atomic-openshift-utils
    yum: name={{ item }} state=present
    with_items:
      - libselinux-python
      - atomic-openshift-utils



